baseURL: https://satrio.dev/
theme: "PaperMod"
languageCode: id-ID
title: Satriyo Unggul Wicaksono
pagination:
  pagerSize: 10

enableRobotsTXT: true
buildDrafts: true
buildFuture: true
buildExpired: true

minify:
  disableXML: true
  minifyOutput: true
  
disqusShortname: satriodev-1

params:
  env: production
  title: Satriyo Unggul Wicaksono
  description: "Personal site of Satriyo Unggul Wicaksono, Sharing about programming, career, and life."
  keywords: [Blog, Portfolio, Satriyo, JavaScript, Python, Programming, Laravel, PHP, Career]
  author: Satriyo
  images: ["https://lh3.googleusercontent.com/a/ALm5wu03kN6nHsy37vGIsHNzkp7xXDURKnmNulwSjNuJ=s288-p-rw-no"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    favicon: "/img/favicon.png"
    favicon16x16: "/img/favicon-16x16.png"
    favicon32x32: "/img/favicon-32x32.png"
    apple_touch_icon: "/img/apple-touch-icon.png"
    safari_pinned_tab: "/img/safari-pinned-tab.svg"

  label:
    text: "satrio.dev"
    icon: /apple-touch-icon.png
    iconHeight: 35

  profileMode:
    enabled: false
    title: satrio.dev
    subtitle: "Personal site of Satriyo"
    imageUrl: "https://lh3.googleusercontent.com/a/ALm5wu03kN6nHsy37vGIsHNzkp7xXDURKnmNulwSjNuJ=s288-p-rw-no"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my profile
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/"

  analytics:
    google:
      SiteVerificationTag: "G-VF1WERHTLN"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  editPost:
    URL: "https://github.com/satrijo/personal/tree/master/content"
    Text: "Suggest Changes"
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: Home
      name: Home
      url: /
      weight: 10
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: LinkedIn
      name: LinkedIn
      url: https://www.linkedin.com/in/satriyounggulwicaksono/
      weight: 40
    - identifier: GitHub
      name: GitHub
      url: https://github.com/satrijo
      weight: 50

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false